spring.application.name=ProducerMessagingProject
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.datasource.url=jdbc:postgresql://localhost:5433/messaging_project
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#send to environment variable at production
jwt.jwtKey=7hQm3v9kL2sP8xZr4nF6dJ1cT5uY0bW8
jwt.jwtSignatureAlgorithm=HmacSHA256
jwt.jwtExpirationMinutes=120

